{{--
    Provenance block (frozen §15) — the trust footer printed on every page.
    Carries the Report Version, who/when generated, the page counter (CSS
    counters), the system-generated line, and the generator (renderer) tag.
    All fields come from ReportMeta.
--}}
<div class="report-footer-grid">
    <div class="rf-col rf-left">
        <span class="rf-label">Generated by</span>
        <span class="rf-value">{{ $meta->generatedByName }}</span>
        <span class="rf-version">Report version {{ $meta->reportVersion }}</span>
    </div>
    <div class="rf-col rf-center">
        <span class="rf-system">System-generated report — JewelFlow</span>
        <span class="rf-tag">{{ $meta->generatorTag }}</span>
    </div>
    <div class="rf-col rf-right">
        <span class="rf-label">Generated at</span>
        <span class="rf-value">{{ $meta->generatedAt->format('d M Y, g:i A') }} ({{ $meta->generatedAt->format('T') }})</span>
        <span class="rf-pages">Page <span class="rf-page-num"></span> of <span class="rf-page-count"></span></span>
    </div>
</div>
