<?php

namespace App\Services\Reporting\Render\Excel;

use App\Services\Reporting\Dataset\ReportMeta;
use Maatwebsite\Excel\Concerns\FromArray;
use Maatwebsite\Excel\Concerns\ShouldAutoSize;
use Maatwebsite\Excel\Concerns\WithEvents;
use Maatwebsite\Excel\Concerns\WithTitle;
use Maatwebsite\Excel\Events\AfterSheet;

/**
 * The "Report Info" sheet (frozen §5.2) — carries the same provenance metadata
 * as the PDF header / CSV sidecar: shop, GSTIN, report, period, filters applied,
 * generated by/at, profile, version, watermark. Kept on its own sheet so the
 * data sheets stay clean single tables with no banner rows.
 */
final class ReportInfoSheet implements FromArray, WithTitle, WithEvents, ShouldAutoSize
{
    public function __construct(private readonly ReportMeta $meta)
    {
    }

    /**
     * @return array<int, array<int, string>>
     */
    public function array(): array
    {
        $m = $this->meta;

        $rows = [
            ['Field', 'Value'],
            ['Report', $m->title],
            ['Report key', $m->reportKey],
            ['Version', $m->reportVersion],
            ['Profile', $m->profileLabel],
            ['Format', $m->format],
            ['Period', $m->periodLabel ?? ''],
            ['Shop', $m->shopLegalName],
            ['Address', $m->shopAddress ?? ''],
            ['GSTIN', $m->shopGstin ?? ''],
            ['State code', $m->shopStateCode ?? ''],
            ['Generated by', $m->generatedByName],
            ['Generated at', $m->generatedAt->format('d M Y, g:i A') . ' (' . $m->generatedAt->format('T') . ')'],
            ['Generator', $m->generatorTag],
        ];

        if ($m->hasWatermark()) {
            $rows[] = ['Watermark', (string) $m->watermark];
        }

        // Filters applied — one row per filter, clearly under a sub-heading row.
        if (! empty($m->filtersApplied)) {
            $rows[] = ['', ''];
            $rows[] = ['Filters applied', ''];
            foreach ($m->filtersApplied as $key => $value) {
                $rows[] = [(string) $key, (string) $value];
            }
        }

        return $rows;
    }

    public function title(): string
    {
        return 'Report Info';
    }

    /**
     * @return array<class-string, callable>
     */
    public function registerEvents(): array
    {
        return [
            AfterSheet::class => function (AfterSheet $event): void {
                $sheet = $event->sheet->getDelegate();
                $sheet->getStyle('A1:B1')->getFont()->setBold(true);
                $sheet->getStyle('A1:B1')->getFill()
                    ->setFillType(\PhpOffice\PhpSpreadsheet\Style\Fill::FILL_SOLID)
                    ->getStartColor()->setARGB('FFF0FDFA');
                $sheet->getColumnDimension('A')->setWidth(22);
            },
        ];
    }
}
