<?php

namespace App\Http\Controllers;

use App\Models\Item;
use App\Models\Shop;
use App\Services\CatalogShareService;
use Illuminate\Http\JsonResponse;
use Illuminate\Http\Request;

class CatalogController extends Controller
{
    public function __construct(private CatalogShareService $catalog) {}

    /**
     * WhatsApp catalog sharing page — lists in-stock items with shareable links.
     */
    public function index(Request $request)
    {
        $shop = auth()->user()->shop;
        if ($shop) {
            $shop->loadMissing('catalogWebsiteSettings');
        }

        $query = Item::where('shop_id', $shop->id)
            ->where('status', 'in_stock');

        if ($request->filled('search')) {
            $search = trim((string) $request->input('search'));
            $query->where(function ($q) use ($search) {
                $q->where('barcode', 'ilike', "%{$search}%")
                    ->orWhere('design', 'ilike', "%{$search}%")
                    ->orWhere('category', 'ilike', "%{$search}%")
                    ->orWhere('sub_category', 'ilike', "%{$search}%")
                    ->orWhere('huid', 'ilike', "%{$search}%");
            });
        }

        if ($request->filled('category')) {
            $query->where('category', $request->category);
        }

        if ($request->filled('sub_category')) {
            $query->where('sub_category', $request->sub_category);
        }

        $allMatchingIds = (clone $query)->pluck('id')->map(fn ($id) => (string) $id)->values()->toArray();

        $items = $query->latest()->paginate(20);

        // Tokens are pre-generated by migration — this only fires as a safety net
        // for items created after the migration but before the token was assigned.
        $items->getCollection()->transform(function (Item $item) use ($shop) {
            $token = $this->catalog->ensureItemHasToken($item);
            $item->public_share_url = $this->buildProductShareUrl($shop, $token);
            return $item;
        });

        $categories = Item::where('shop_id', $shop->id)
            ->where('status', 'in_stock')
            ->whereNotNull('category')
            ->where('category', '!=', '')
            ->distinct()
            ->pluck('category')
            ->filter()
            ->sort()
            ->values();

        $subCategories = Item::where('shop_id', $shop->id)
            ->where('status', 'in_stock')
            ->whereNotNull('sub_category')
            ->where('sub_category', '!=', '')
            ->when($request->filled('category'), fn ($q) => $q->where('category', $request->category))
            ->distinct()
            ->pluck('sub_category')
            ->filter()
            ->sort()
            ->values();

        $preferences   = $shop->preferences;
        $savedWaHeader = $preferences->wa_custom_header ?? null;
        $savedWaBody   = $preferences->wa_custom_body   ?? null;
        $savedWaFooter = $preferences->wa_custom_footer ?? null;

        return view('retailer-reports.whatsapp', compact(
            'items', 'categories', 'subCategories', 'savedWaHeader', 'savedWaBody', 'savedWaFooter', 'allMatchingIds'
        ));
    }

    /**
     * Create a shareable collection link from selected item IDs.
     */
    public function storeCollection(Request $request): JsonResponse
    {
        $shop = auth()->user()->shop;
        if ($shop) {
            $shop->loadMissing('catalogWebsiteSettings');
        }

        $validated = $request->validate([
            'item_ids'   => ['required', 'array', 'min:1'],
            'item_ids.*' => ['integer'],
            'title'      => ['nullable', 'string', 'max:120'],
        ]);

        $itemIds = collect($validated['item_ids'])
            ->map(fn ($id) => (int) $id)
            ->filter(fn ($id) => $id > 0)
            ->unique()
            ->values()
            ->all();

        if (empty($itemIds)) {
            return response()->json(['message' => 'Select at least one valid product.'], 422);
        }

        try {
            $collection = $this->catalog->createCollection(
                $shop,
                auth()->user(),
                $itemIds,
                $validated['title'] ?? null
            );
        } catch (\Illuminate\Validation\ValidationException $e) {
            return response()->json(['message' => $e->validator->errors()->first()], 422);
        }

        return response()->json([
            'message' => 'Collection link created successfully.',
            'url'     => $this->buildCollectionShareUrl($shop, (string) $collection->token),
            'count'   => count($itemIds),
        ]);
    }

    private function buildProductShareUrl(?Shop $shop, string $token): string
    {
        return $this->catalog->buildPreferredProductUrl($shop, $token);
    }

    private function buildCollectionShareUrl(?Shop $shop, string $token): string
    {
        return $this->catalog->buildPreferredCollectionUrl($shop, $token);
    }
}
