<?php

namespace Tests\Unit\Reporting\Render;

use App\Services\Reporting\Definition\ExportFormat as F;
use App\Services\Reporting\Render\CsvRenderer;
use PHPUnit\Framework\TestCase;
use ZipArchive;

/**
 * Clean machine-CSV (frozen §5.3): single header row + raw-value rows, ISO
 * dates, raw decimals, no ₹, no banner/blank/label rows. Multi-section → ZIP.
 */
class CsvRendererTest extends TestCase
{
    use RendererFixtures;

    public function test_single_section_is_one_clean_table(): void
    {
        $dataset = $this->singleSectionDataset();
        $out = (new CsvRenderer())->render($dataset, $this->fixtureRequest($dataset, F::Csv));

        $this->assertSame('text/csv', $out->mimeType);
        $this->assertStringEndsWith('.csv', $out->filename);

        $lines = array_values(array_filter(explode("\n", trim($out->contents)), static fn ($l) => $l !== ''));

        // Header + exactly 2 data rows — no banner, no blank, no label rows.
        $this->assertCount(3, $lines);
        $this->assertStringContainsString('Invoice No', $lines[0]);
        $this->assertStringContainsString('GST %', $lines[0]);
    }

    public function test_raw_values_iso_dates_no_rupee(): void
    {
        $dataset = $this->singleSectionDataset();
        $out = (new CsvRenderer())->render($dataset, $this->fixtureRequest($dataset, F::Csv));

        $this->assertStringNotContainsString('₹', $out->contents);
        $this->assertStringNotContainsString(',34,', $out->contents, 'No thousands grouping in CSV.');

        // ISO date and raw decimal present.
        $this->assertStringContainsString('2025-04-12', $out->contents);
        $this->assertStringContainsString('1234567.50', $out->contents);
        $this->assertStringContainsString('12.345', $out->contents);

        // Booleans as true/false.
        $this->assertStringContainsString('true', $out->contents);
        $this->assertStringContainsString('false', $out->contents);
    }

    public function test_no_metadata_inside_csv(): void
    {
        $dataset = $this->singleSectionDataset();
        $out = (new CsvRenderer())->render($dataset, $this->fixtureRequest($dataset, F::Csv));

        // Provenance must never leak into the CSV body.
        $this->assertStringNotContainsString('Shyam Jewellers', $out->contents);
        $this->assertStringNotContainsString('Generated by', $out->contents);
        $this->assertStringNotContainsString('GSTIN', $out->contents);
    }

    public function test_multi_section_produces_zip_with_per_section_csvs_and_meta(): void
    {
        $dataset = $this->multiSectionDataset();
        $out = (new CsvRenderer())->render($dataset, $this->fixtureRequest($dataset, F::Csv));

        $this->assertSame('application/zip', $out->mimeType);
        $this->assertStringEndsWith('.zip', $out->filename);

        $tmp = tempnam(sys_get_temp_dir(), 'csvtest');
        file_put_contents($tmp, $out->contents);

        $zip = new ZipArchive();
        $this->assertTrue($zip->open($tmp) === true);

        $names = [];
        for ($i = 0; $i < $zip->numFiles; $i++) {
            $names[] = $zip->getNameIndex($i);
        }

        $this->assertContains('b2b.csv', $names);
        $this->assertContains('b2cs.csv', $names);

        $metaFiles = array_filter($names, static fn ($n) => str_ends_with($n, '-meta.json'));
        $this->assertCount(1, $metaFiles, 'Exactly one provenance sidecar.');

        // The per-section CSV is itself clean (header + 2 rows for b2b).
        $b2b = $zip->getFromName('b2b.csv');
        $b2bLines = array_values(array_filter(explode("\n", trim((string) $b2b)), static fn ($l) => $l !== ''));
        $this->assertCount(3, $b2bLines);
        $this->assertStringContainsString('GSTIN', $b2bLines[0]);

        // Sidecar carries provenance.
        $metaName = array_values($metaFiles)[0];
        $meta = json_decode((string) $zip->getFromName($metaName), true);
        $this->assertSame('gstr1', $meta['reportKey']);
        $this->assertSame('Shyam Jewellers Pvt Ltd', $meta['shopLegalName']);

        $zip->close();
        @unlink($tmp);
    }
}
